name: CI/CD Pipeline

on:
  push:
  pull_request:
    branches: [ "master", "qa" ]
    # É fundamental listar os 'types' para que o evento 'closed' seja escutado!
    types: [opened, synchronize, reopened, closed]

# A permissão DEVE ficar na raiz do consumidor para autorizar o orquestrador a criar a tag
permissions:
  contents: write

jobs:
  pipeline:
    uses: KaueTTS/ci-templates/.github/workflows/golang.yml@main
    with:
      go_version: '1.25'
      min_coverage: '20'
      binary_name: 'streaming-api' 
      exclude_packages: '/shared|/mocks|/models|/dto|/container'
      build_path: '.'
      target_branch: 'master'
      source_branch: 'qa'
    secrets: inherit